apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-stateful
  labels:
    app: mydb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydb
  serviceName: db-service
  minReadySeconds: 10
  template:
    metadata:
      name: db-pod
      labels:
        app: mydb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: db-image
          image: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data_1
              name: db-data-postgre
          env:
            - name: POSTGRES_DB
              value: registry
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
    
#          livenessProbe:
 #           exec:
  #            command:
   #             - pg_isready -U postgres
    #        periodSeconds: 5
     #       timeoutSeconds: 10
      #      failureThreshold: 5
      volumes:
        - name: db-data-postgre
          hostPath:
            path: /home/ubuntu/
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: mydb
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  username: "cG9zdGdyZXM="
  password: "cG9zdGdyZXM="
