apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: es-pods
      labels:
        app: myapp
    spec:
      containers:
       -  name: es
          image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
          env:
           - name: discovery.type
             value: single-node
           - name: ES_JAVA_OPTS
             value: -Xms512m -Xmx512m
           - name: xpack.security.enabled
             value: "false"
           - name: Elastic_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: es-secret
                 key: password
         # livenessProbe:
          #  exec:
           #   command:
            #    - curl -f localhost:9200/_cluster/health --header Authorization:Basic ZWxhc3RpYzpEa0llZFBQU0Ni 
           # periodSeconds: 30
           # timeoutSeconds: 10
          #  failureThreshold: 4 
---

apiVersion: v1
kind: Service
metadata:
  name: es-service
spec:
  selector:
      app: myapp
  ports:
   - name: "9200"
     port: 9200
     targetPort: 9200
   - name: "9300"
     port: 9300
     targetPort: 9300

---

apiVersion: v1
kind: Secret
metadata: 
  name: es-secret
type: Opaque
data:
  password: "ZWxhc3RpYw=="
