apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kc-app
  template:
    metadata:
      name: pod-keyclock
      labels:
        app: kc-app
    spec:
      containers:
        - name: kc-container
          image: dockerhub/sunbird-rc-keycloak:latest
          volumeMounts:
            - name: kc-vol
              mountPath: /opt/jboss/keycloak/imports
          env:
            - name: KEYCLOAK_LOGO
              value: https://svgshare.com/i/hCs.svg
            - name: DB_VENDOR
              value: postgres
            - name: DB_ADDR
              value: db-service
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: registry
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: kc-secret
                  key: username1
              # value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kc-secret
                  key: password1
              # value: postgres
            - name: KEYCLOAK_USER
              valueFrom:
                secretKeyRef:
                  name: kc-secret
                  key: username2
              # value: admin
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kc-secret
                  key: password2
              # value: admin
            - name: KEYCLOAK_IMPORT
              value: /opt/jboss/keycloak/imports/realm-export.json
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
#          livenessProbe:
 #           exec:
  #            command:
   #             - curl -f http://localhost:9990/ || exit 1
    #        periodSeconds: 30
     #       timeoutSeconds: 10
      #      failureThreshold: 10
#      initContainers:
 #       - name: db
  #        image: postgres

      volumes:
        - name: kc-vol
          hostPath:
            path: /home/ubuntu/imports

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: NodePort
  selector:
    app: kc-app
  ports:
    - nodePort: 31114
      name: kc-port1
      targetPort: 8080
      port: 8080
    - nodePort: 31115
      name: kc-port2
      targetPort: 9990
      port: 9990

---
apiVersion: v1 
kind: Secret 
metadata: 
  name: kc-secret
type: Opaque
data:
  username1 : "cG9zdGdyZXM="
  password1 : "cG9zdGdyZXM="
  username2 : "YWRtaW4="
  password2 : "YWRtaW4="