apiVersion: apps/v1
kind: Deployment
metadata:
  name: digi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digi-app
  template:
    metadata:
      name: digi-pod
      labels:
        app: digi-app
    spec:
      containers:
        - name: digi-container
          image: dockerhub/sunbird-rc-digilocker-certificate-api
          env:
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: digi-config
                  key: KEYCLOAK_CLIENT_ID
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: digi-config
                  key: KEYCLOAK_CLIENT_SECRET
            - name: DIGILOCKER_HMAC_AUTHKEY
              valueFrom:
                configMapKeyRef:
                  name: digi-config
                  key: DIGILOCKER_HMAC_AUTHKEY
            - name: DIGILOCKER_AUTH_KEYNAME
              valueFrom:
                configMapKeyRef:
                  name: digi-config
                  key: DIGILOCKER_AUTH_KEYNAME
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: digi-config
                  key: PORT
          volumeMounts:
            - name: digi-vol
              mountPath: /go/config/
      volumes:
        - name: digi-vol
          # persistentVolumeClaim:
          #   claimName: digi-pvc
          hostPath:
            path: /home/ubuntu/services/digilocker-certificate-api/config
---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: digi-pv
# spec:
#   capacity:
#     storage: 500Mi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce 
#   storageClassName: local-storage
#   local:
#     path: /home/ubuntu/services/digilocker-certificate-api/config
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - ip-172-18.0.2

---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: digi-pvc
# spec:
#   volumeName: digi-pv
#   storageClassName: local-storage
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce 
#   resources:
#     requests:
#       storage: 500Mi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: digi-config
data:
  KEYCLOAK_CLIENT_ID: admin-api
  KEYCLOAK_CLIENT_SECRET: SECRET
  DIGILOCKER_HMAC_AUTHKEY: AUTHKEY
  DIGILOCKER_AUTH_KEYNAME: x-digilocker-hmac
  PORT: "8087"

---
apiVersion: v1
kind: Service
metadata:
  name: digi-service
spec:
  selector:
    app: digi-app
  ports:
    - name: "8087"
      port: 8087
      targetPort: 8087
