apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-container
          image: dockerhub/sunbird-rc-nginx
#          livenessProbe:
 #           exec:
  #            command:
   #             - curl -f localhost:80
    #        periodSeconds: 30
     #       timeoutSeconds: 10
      #      failureThreshold: 10
#      initContainers:
#        - name: registry
 #         image: dockerhub/sunbird-rc-core:v0.0.14
  #      - name: context-proxy-service
   #       image: dockerhub/sunbird-rc-context-proxy-service
    #    - name: public-key-service
     #     image: dockerhub/sunbird-rc-public-key-service
     #   - name: keycloak
     #     image: dockerhub/sunbird-rc-keycloak:latest
   #     - name: claim-ms
   #       image: dockerhub/sunbird-rc-claim-ms:v0.0.14
   #     - name: file-storage
    #      image: quay.io/minio/minio

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
    - name: "80"
      port: 80
      nodePort: 31130
      targetPort: 80
